### ISSUE TITLE
Stack Allocator

### ISSUE THREAD

**Issue by t81lal** [LLVM-but-worse/maple-ir#15]
We need to verify the integrity of the output code.
There is a DVB test case with natural flow into handlers and the regenerated bytecode is illegal. This would probably need a stack allocator to fix or maybe special handling for outputting code.

**Comment by ecx86** [comment]
I'm not sure about this. The IR should be correct regardless of the allocator, and currently the allocator just converts all remaining stack variables after optimization into local variables. Why is it broken?

Stack allocator would be nice to have, but I think the issue is probably comes from the generation or optimization phase.
